[workspace]
resolver = "2"
members = [
    "blueprints/unit-tests",
    "blueprints/adapters-interface",
    "blueprints/ociswap-adapter",
    "blueprints/olympus",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "The implementation of project Olympus in Scrypto for the Radix Ledger"

[workspace.dependencies]
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
radix-engine-stores = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
radix-engine-queries = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
radix-engine-store-interface = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
radix-engine-interface = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }

scrypto-unit = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }
scrypto-test = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "2d0ba81f5e6a774056783e990745c916856f6fdc" }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
overflow-checks = true
