[config]
default_to_workspace = false

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.check]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.publish-stokenet]
command = "cargo"
args = [
    "run",
    "--package",
    "bootstrapper",
    "--",
    "publish-test-to-stokenet",
    "./frontend/public/config.json",
    "./frontend/src/config.json",
]

[tasks.frontend-start]
command = "npm"
args = ["start", "--prefix", "./frontend"]
