[config]
default_to_workspace = false

[tasks.test]
install_crate = "nextest"
command = "cargo"
args = ["nextest", "run", "--features", "compile-blueprints-at-build-time"]

[tasks.check]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]