[package]
name = "simple-oracle"
version = { workspace = true }
edition = { workspace = true }
description = "A simple oracle used in tests."

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
radix-engine-derive = { workspace = true }

scrypto-interface = { path = "../../libraries/scrypto-interface" }
adapters-interface = { path = "../../libraries/adapters-interface" }

humantime = { version = "2.1.0" }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
