[package]
name = "caviarnine-v1-adapter-v1"
version.workspace = true
edition.workspace = true
description = "Defines the adapter for Caviarnine"

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
radix-engine-interface = { workspace = true }
transaction = { workspace = true, optional = true }

scrypto-interface = { path = "../../libraries/scrypto-interface" }
ports-interface = { path = "../../libraries/ports-interface" }

[features]
default = []
test = []

manifest-builder-stubs = ["dep:transaction"]

[lib]
crate-type = ["cdylib", "lib"]
