[package]
name = "ignition"
version.workspace = true
edition.workspace = true
description = "The implementation of the Ignition protocol"

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
radix-engine-derive = { workspace = true }

ports-interface = { path = "../../libraries/ports-interface" }
common = { path = "../../libraries/common" }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true