[package]
name = "unit-tests"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
