name: Test
on:
  pull_request:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Install cargo nextest
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
        locked: true
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Run tests
      run: cargo nextest run --features compile-blueprints-at-build-time
      env:
        # Enable sccache
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Check formatting
      run: cargo fmt --check
      env:
        # Enable sccache
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
  cargo-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Cargo Check
      run: cargo check --all
      env:
        # Enable sccache
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
  clippy-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Clippy Check
      run: cargo clippy --all
      env:
        # Enable sccache
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"